name: davidsaville
favicon: null
layout_spectrum: 0.25
typography_spectrum: 0.53339
title: David Saville Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010006'
    - '#225037'
    - '#488162'
    - '#67a394'
    - '#fcfefd'
  brandStrength: 0.5
  lightness: 0.6503726877272129
  saturation: 0.16468372475355864
  rhythmicContrast: 0.24835260841064155
purpose: []
